name: Update Commit Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install PyGithub

    - name: Update Commit Stats
      run: python commit_stats.py

    - name: Commit and push changes
      run: |
        git config user.name "Your Name"
        git config user.email "youremail@example.com"
        git add README.md
        git commit -m "Update commit stats"
        git push
